version: 2.1
jobs:
  hygiene_tests:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hygiene tests
          command: .hygiene/run_hygiene.sh
      - store_test_results:
          path: /output
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - hygiene_tests
