title: Making Study Populations Visible through Knowledge Graphs
description: A website to navigate resources open-sourced via the associated ISWC 2019 paper
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky

baseurl:          https://tetherless-world.github.io/ontology-engineering/oe2020/project1/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:   https://github.com/tetherless-world/ontology-engineering/tree/master/oe2020/project1
  
sass:
  sass_dir: assets\css
